export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const AUTH_API_CALL_START = "AUTH_API_CALL_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const API_CALL_BEGIN = "API_CALL_BEGIN";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAILURE = "LOAD_USERS_FAILURE";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAILURE = "REMOVE_USER_FAILURE";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const LOAD_ATTENDANCES_SUCCESS = "LOAD_ATTENDANCES_SUCCESS";
export const LOAD_ATTENDANCES_FAILURE = "LOAD_ATTENDANCES_FAILURE";

export const ADD_USER_ATTENDANCE_SUCCESS = "ADD_USER_ATTENDANCE_SUCCESS";
export const ADD_USER_ATTENDANCE_FAILURE = "ADD_USER_ATTENDANCE_FAILURE";

export const LOAD_USER_ATTENDANCE_SUCCESS = "LOAD_USER_ATTENDANCE_SUCCESS";
export const LOAD_USER_ATTENDANCE_FAILURE = "LOAD_USER_ATTENDANCE_FAILURE ";

export const UPDATE_ATTENDANCE_SUCCESS = "UPDATE_ATTENDANCE_SUCCESS";
export const UPDATE_ATTENDANCE_FAILURE = "UPDATE_ATTENDANCE_FAILURE ";
